#!/bin/sh

hsetroot -cover /home/void/dots/Wallpapers/voidlogotext.png &

picom --experimental-backends & 

light -S 10 &

pgrep -x sxhkd > /dev/null || sxhkd &

pgrep -x greenclip > /dev/null || greenclip daemon &

/usr/bin/pactl set-sink-volume alsa_output.pci-0000_00_1f.3.analog-stereo 30% &

pgrep -x redshift > /dev/null || redshift &

xinput set-prop SynPS/2\ Synaptics\ TouchPad "libinput Tapping Enabled"  1 &
xinput set-prop SynPS/2\ Synaptics\ TouchPad "libinput Middle Emulation Enabled"  1 &
xinput set-prop SynPS/2\ Synaptics\ TouchPad "libinput Natural Scrolling Enabled" 1

~/.dwm/bars/onedark.sh &

dwm
